#!/bin/bash
####################################
#
# Backup to NFS mount script.
#
####################################
./../build/mvbb_object_decomposition_example  cheezit_big_original < ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/cheezit_big_original/meshes/tsdf_reduced.shl
./../build/mvbb_object_decomposition_example  crayola_64_ct < ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/crayola_64_ct/meshes/tsdf_reduced.shl 
./../build/mvbb_object_decomposition_example  dove_beauty_bar < ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/dove_beauty_bar/meshes/tsdf_reduced.shl 
./../build/mvbb_object_decomposition_example  dr_browns_bottle_brush < ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/dr_browns_bottle_brush/meshes/tsdf_reduced.shl 
./../build/mvbb_object_decomposition_example  elmers_washable_no_run_school_glue < ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/elmers_washable_no_run_school_glue/meshes/tsdf_reduced.shl 
./../build/mvbb_object_decomposition_example  expo_dry_erase_board_eraser < ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/expo_dry_erase_board_eraser/meshes/tsdf_reduced.shl 
./../build/mvbb_object_decomposition_example  feline_greenies_dental_treats < ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/feline_greenies_dental_treats/meshes/tsdf_reduced.shl 
./../build/mvbb_object_decomposition_example  first_years_take_and_toss_straw_cups < ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/first_years_take_and_toss_straw_cups/meshes/tsdf_reduced.shl 
./../build/mvbb_object_decomposition_example  genuine_joe_plastic_stir_sticks < ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/genuine_joe_plastic_stir_sticks/meshes/tsdf_reduced.shl 
./../build/mvbb_object_decomposition_example  highland_6539_self_stick_notes < ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/highland_6539_self_stick_notes/meshes/tsdf_reduced.shl 
./../build/mvbb_object_decomposition_example  kong_air_dog_squeakair_tennis_ball < ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/kong_air_dog_squeakair_tennis_ball/meshes/tsdf_reduced.shl 
./../build/mvbb_object_decomposition_example  kong_sitting_frog_dog_toy < ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/kong_sitting_frog_dog_toy/meshes/tsdf_reduced.shl 
./../build/mvbb_object_decomposition_example  kygen_squeakin_eggs_plush_puppies < ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/kygen_squeakin_eggs_plush_puppies/meshes/tsdf_reduced.shl 
./../build/mvbb_object_decomposition_example  laugh_out_loud_joke_book < ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/laugh_out_loud_joke_book/meshes/tsdf_reduced.shl 
./../build/mvbb_object_decomposition_example  mark_twain_huckleberry_finn < ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/mark_twain_huckleberry_finn/meshes/tsdf_reduced.shl 
./../build/mvbb_object_decomposition_example  mead_index_cards < ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/mead_index_cards/meshes/tsdf_reduced.shl 
./../build/mvbb_object_decomposition_example  mommys_helper_outlet_plugs < ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/mommys_helper_outlet_plugs/meshes/tsdf_reduced.shl 
./../build/mvbb_object_decomposition_example  munchkin_white_hot_duck_bath_toy < ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/munchkin_white_hot_duck_bath_toy/meshes/tsdf_reduced.shl 
./../build/mvbb_object_decomposition_example  one_with_nature_soap_dead_sea_mud < ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/one_with_nature_soap_dead_sea_mud/meshes/tsdf_reduced.shl 
./../build/mvbb_object_decomposition_example  oreo_mega_stuf < ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/oreo_mega_stuf/meshes/tsdf_reduced.shl 
./../build/mvbb_object_decomposition_example  paper_mate_12_count_mirado_black_warrior < ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/paper_mate_12_count_mirado_black_warrior/meshes/tsdf_reduced.shl 
./../build/mvbb_object_decomposition_example  rollodex_mesh_collection_jumbo_pencil_cup < ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/rollodex_mesh_collection_jumbo_pencil_cup/meshes/tsdf_reduced.shl 
./../build/mvbb_object_decomposition_example  safety_works_safety_glasses < ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/safety_works_safety_glasses/meshes/tsdf_reduced.shl 
./../build/mvbb_object_decomposition_example  sharpie_accent_tank_style_highlighters < ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/sharpie_accent_tank_style_highlighters/meshes/tsdf_reduced.shl 
./../build/mvbb_object_decomposition_example  stanley_66_052 < ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/stanley_66_052/meshes/tsdf_reduced.shl 
./../build/mvbb_object_decomposition_example  1_and_a_half_in_metal_washer < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/1_and_a_half_in_metal_washer/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  1in_metal_washer < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/1in_metal_washer/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  2in_metal_washer < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/2in_metal_washer/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  black_and_decker_lithium_drill_driver < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/black_and_decker_lithium_drill_driver/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  black_and_decker_lithium_drill_driver_unboxed < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/black_and_decker_lithium_drill_driver_unboxed/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  blank_hard_plastic_card < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/blank_hard_plastic_card/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  block_of_wood_12in < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/block_of_wood_12in/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  block_of_wood_6in < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/block_of_wood_6in/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  blue_wood_block_1inx1in < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/blue_wood_block_1inx1in/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  brine_mini_soccer_ball < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/brine_mini_soccer_ball/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  campbells_condensed_tomato_soup < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/campbells_condensed_tomato_soup/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  champion_sports_official_softball < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/champion_sports_official_softball/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  cheerios_14oz < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/cheerios_14oz/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  cheeze-it_388g < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/cheeze-it_388g/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  clorox_disinfecting_wipes_35 < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/clorox_disinfecting_wipes_35/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  comet_lemon_fresh_bleach < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/comet_lemon_fresh_bleach/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  dark_red_foam_block_with_three_holes < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/dark_red_foam_block_with_three_holes/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  domino_sugar_1lb < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/domino_sugar_1lb/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  expo_black_dry_erase_marker < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/expo_black_dry_erase_marker/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  expo_black_dry_erase_marker_fine < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/expo_black_dry_erase_marker_fine/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  extra_small_black_spring_clamp < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/extra_small_black_spring_clamp/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  frenchs_classic_yellow_mustard_14oz < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/frenchs_classic_yellow_mustard_14oz/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  jell-o_chocolate_flavor_pudding < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/jell-o_chocolate_flavor_pudding/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  jell-o_strawberry_gelatin_dessert < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/jell-o_strawberry_gelatin_dessert/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  large_black_spring_clamp < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/large_black_spring_clamp/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  learning_resources_one-inch_color_cubes_box < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/learning_resources_one-inch_color_cubes_box/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  master_chef_ground_coffee_297g < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/master_chef_ground_coffee_297g/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  medium_black_spring_clamp < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/medium_black_spring_clamp/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  melissa_doug_farm_fresh_fruit_apple < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/melissa_doug_farm_fresh_fruit_apple/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  melissa_doug_farm_fresh_fruit_banana < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/melissa_doug_farm_fresh_fruit_banana/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  melissa_doug_farm_fresh_fruit_lemon < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/melissa_doug_farm_fresh_fruit_lemon/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  melissa_doug_farm_fresh_fruit_orange < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/melissa_doug_farm_fresh_fruit_orange/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  melissa_doug_farm_fresh_fruit_peach < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/melissa_doug_farm_fresh_fruit_peach/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  melissa_doug_farm_fresh_fruit_pear < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/melissa_doug_farm_fresh_fruit_pear/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  melissa_doug_farm_fresh_fruit_plum < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/melissa_doug_farm_fresh_fruit_plum/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  melissa_doug_farm_fresh_fruit_strawberry < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/melissa_doug_farm_fresh_fruit_strawberry/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  melissa_doug_play-time_produce_farm_fresh_fruit_unopened_box < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/melissa_doug_play-time_produce_farm_fresh_fruit_unopened_box/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  morton_pepper_shaker < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/morton_pepper_shaker/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  morton_salt_shaker < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/morton_salt_shaker/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  moutain_security_steel_shackle < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/moutain_security_steel_shackle/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  moutain_security_steel_shackle_key < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/moutain_security_steel_shackle_key/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  orange_wood_block_1inx1in < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/orange_wood_block_1inx1in/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  penn_raquet_ball < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/penn_raquet_ball/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  plastic_bolt_grey < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/plastic_bolt_grey/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  plastic_nut_grey < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/plastic_nut_grey/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  plastic_wine_cup < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/plastic_wine_cup/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  play_go_rainbow_stakin_cups_10_blue < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/play_go_rainbow_stakin_cups_10_blue/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  play_go_rainbow_stakin_cups_1_yellow < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/play_go_rainbow_stakin_cups_1_yellow/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  play_go_rainbow_stakin_cups_2_orange < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/play_go_rainbow_stakin_cups_2_orange/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  play_go_rainbow_stakin_cups_3_red < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/play_go_rainbow_stakin_cups_3_red/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  play_go_rainbow_stakin_cups_5_green < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/play_go_rainbow_stakin_cups_5_green/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  play_go_rainbow_stakin_cups_6_purple < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/play_go_rainbow_stakin_cups_6_purple/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  play_go_rainbow_stakin_cups_7_yellow < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/play_go_rainbow_stakin_cups_7_yellow/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  play_go_rainbow_stakin_cups_8_orange < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/play_go_rainbow_stakin_cups_8_orange/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  play_go_rainbow_stakin_cups_9_red < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/play_go_rainbow_stakin_cups_9_red/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  play_go_rainbow_stakin_cups_blue_4 < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/play_go_rainbow_stakin_cups_blue_4/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  play_go_rainbow_stakin_cups_box < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/play_go_rainbow_stakin_cups_box/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  pringles_original < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/pringles_original/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  purple_wood_block_1inx1in < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/purple_wood_block_1inx1in/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  red_metal_bowl_white_speckles < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/red_metal_bowl_white_speckles/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  red_metal_cup_white_speckles < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/red_metal_cup_white_speckles/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  red_metal_plate_white_speckles < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/red_metal_plate_white_speckles/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  red_wood_block_1inx1in < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/red_wood_block_1inx1in/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  rubbermaid_ice_guard_pitcher_blue < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/rubbermaid_ice_guard_pitcher_blue/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  sharpie_marker < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/sharpie_marker/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  small_black_spring_clamp < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/small_black_spring_clamp/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  soft_scrub_2lb_4oz < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/soft_scrub_2lb_4oz/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  spam_12oz < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/spam_12oz/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  sponge_with_textured_cover < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/sponge_with_textured_cover/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  stainless_steel_fork_red_handle < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/stainless_steel_fork_red_handle/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  stainless_steel_knife_red_handle < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/stainless_steel_knife_red_handle/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  stainless_steel_spatula < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/stainless_steel_spatula/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  stainless_steel_spoon_red_handle < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/stainless_steel_spoon_red_handle/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  stanley_13oz_hammer < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/stanley_13oz_hammer/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  stanley_flathead_screwdriver < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/stanley_flathead_screwdriver/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  stanley_philips_screwdriver < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/stanley_philips_screwdriver/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  starkist_chunk_light_tuna < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/starkist_chunk_light_tuna/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  sterilite_bin_12qt_bottom < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/sterilite_bin_12qt_bottom/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  sterilite_bin_12qt_cap < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/sterilite_bin_12qt_cap/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  thick_wood_block_6in < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/thick_wood_block_6in/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  wearever_cooking_pan_with_lid < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/wearever_cooking_pan_with_lid/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  wescott_orange_grey_scissors < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/wescott_orange_grey_scissors/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  white_rope < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/white_rope/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  wilson_100_tennis_ball < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/wilson_100_tennis_ball/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  wilson_golf_ball < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/wilson_golf_ball/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  windex < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/windex/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  yellow_plastic_chain < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/yellow_plastic_chain/meshes/tsdf_mesh_reduced.shl 
./../build/mvbb_object_decomposition_example  yellow_wood_block_1inx1in < ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/yellow_wood_block_1inx1in/meshes/tsdf_mesh_reduced.shl  

